version: '3.4'

services:
  despesas-frontend-react:
    container_name: prod
    image: alexfariakof/despesas-pessoais-react-img
    working_dir: /usr/share/nginx/html
    build:
      context: .
      dockerfile: ./Dockerfile-Production
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      NODE_ENV: production
      DOMAINS: http://alexfariakof.com
      STAGE: production