version: '3.4'

services:
  despesaspessoaisfrontendreact:
    image: despesaspessoaisfrontendreact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
