version: '3.4'

services:
  despesas-frontend-react-local:
    container_name: despesas-frontend-react-local
    image: despesas-frontend-react-local-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80