version: '3.4'

services:
  despesas-pessoais-frontend-react:
    image: alexfariakof/despesas-pessoais-react-local-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000