version: '3.4'

services:
  despesas-frontend-react:
    image: despesas-frontend-react-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
