version: '3.4'

services:
  despesas-frontend-react:
    container_name: local
    image: alexfariakof/despesas-pessoais-react-local-img
    working_dir: /usr/share/nginx/html
    build:
      context: .
      dockerfile: ./Dockerfile.Local
    ports:
      - 3000:3000
    restart: always
    environment:
      NODE_ENV: development
      DOMAINS: http://alexfariakof.dev.com
      STAGE: development      