version: '3.4'

services:
  despsas-pessoais-react:
    image: despsas-pessoais-react-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
