version: '3.4'

services:
  despesas-pessoais-frontend-react:
    image: despesas-pessoais-frontend-react-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 3000:3000
